[[edge_functions]]
function = "geo-block"
path = "/downloads"

[[edge_functions]]
function = "geo-block"
path = "/downloads/*"

[[edge_functions]]
function = "geo-block"
path = "/subtitle-download"

[[edge_functions]]
function = "geo-block"
path = "/subtitle-download/*"
